site_name: ChainFuse Blog
site_url: !ENV [SITE_URL, CF_PAGES_URL, "https://blog.chainfuse.com"]
site_author: ChainFuse
repo_name: ChainFuse/blog
repo_url: https://github.com/ChainFuse/blog
docs_dir: blog
exclude_docs: |
  *.less
theme:
  name: material
  favicon: assets/logo.svg
  logo: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
  # Enables highlighting of source code in code blocks using the highlight.js JavaScript library
  highlightjs: true
  # Lists the homepage in the sidebar menu. As MkDocs requires that the homepage be listed in the nav configuration option, this setting allows the homepage to be included or excluded from the sidebar. Note that the site name/logo always links to the homepage.
  include_homepage_in_sidebar: false
  # One of bottom, top, both , or none. Displays the “Next” and “Previous” buttons accordingly
  prev_next_buttons_location: none
  # The maximum depth of the navigation tree in the sidebar. Default: 4
  navigation_depth: 5
  # Only include the page section headers in the sidebar for the current page
  collapse_navigation: true
  # Only include page titles in the sidebar, excluding all section headers for all pages
  titles_only: false
  # If True, causes the sidebar to scroll with the main page content as you scroll the page
  sticky_navigation: true
  # The locale (language/location) used to build the theme. If your locale is not yet supported, it will fallback to the default
  locale: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for oled dark mode
    - media: "(prefers-color-scheme: dark) and (dynamic-range: high)"
      scheme: oled
      primary: blue
      accent: cyan
      toggle:
        icon: material/lightbulb-night-outline
        name: Switch to light mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark) and (dynamic-range: standard)"
      scheme: darkgray
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to oled dark mode
  font:
    text: Roboto
    code: Red Hat Mono
  features:
    - navigation.instant
    - navigation.instant.progress
  custom_dir: overrides
extra:
  social:
    - icon: fontawesome/brands/threads
      link: https://www.threads.net/@chainfuse
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/chainfuse?igshid=NTc4MTIwNjQ2YQ==
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ChainFuse
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/chainfuse/
extra_css:
  - stylesheets/fullWidth.css
  - stylesheets/theme.css
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: "#"
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
hooks:
  - hooks/preSetup.py
  - hooks/configEdit.py
  - hooks/lessCompiler.py
  - hooks/postSetup.py
plugins:
  - blog:
      blog_dir: .
      blog_toc: true
  - search
  - social:
      enabled: !ENV [ENABLED_SOCIAL, false]
  - tags
  - glightbox:
      auto_caption: true
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
        reduce_boolean_attributes: true
      minify_js: true
      minify_css: true
      cache_safe: true
      css_files:
        - stylesheets/fullWidth.css
        - stylesheets/theme.css
