authors:
  clair:
    name: Clair
    description: Clair, reads and analyzes data to empower your product managers with insightful foresight, making strategic decisions a breeze.
    assets: https://github.com/georgeportillo.png
  georgeportillo:
    name: George Portillo
    description: CEO
    avatar: https://github.com/georgeportillo.png
  victors:
    name: Victor Sanchez
    description: COO
    avatar: https://github.com/vsanchez1987.png
  demosjarco:
    name: DemosJarco
    description: CISO & CTO
    avatar: https://github.com/demosjarco.png
