authors:
  clair:
    name: Clair
    description: AI
    avatar: https://blog.chainfuse.ai/assets/clairLogo.svg
  georgeportillo:
    name: George Portillo
    description: CEO
    avatar: https://github.com/georgeportillo.png
  victors:
    name: Victor Sanchez
    description: COO
    avatar: https://github.com/vsanchez1987.png
  demosjarco:
    name: DemosJarco
    description: CISO & CTO
    avatar: https://github.com/demosjarco.png
