name: Deploy
concurrency: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
      - live
    paths-ignore:
      - ".vscode/**"
      - "_headers"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref || github.ref_name }}
    permissions:
      contents: write
      pages: write
    steps:
      - uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: sudo apt update
      - uses: awalsh128/cache-apt-pkgs-action@1850ee53f6e706525805321a3f2f863dcf73c962 # v1.3.0
        with:
          # Don't include libz-dev due to cache issue
          packages: libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev
      - uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4.8.0
        with:
          python-version: '3.x'
          check-latest: true
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: MkDocs cache
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: mkdocs gh-deploy --force
        env:
          ENABLED_SOCIAL: true
          SITE_URL: https://chainfuse.github.io/blog/
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: site
          path: ${{ github.workspace }}/site/
          if-no-files-found: error